### ISSUE TITLE
Copyright 2020 -> 2021

### ISSUE THREAD

**Issue by l3nnartt** [EngineHub/WorldEditDocs#38]
![Kw98fBD](https://user-images.githubusercontent.com/69513317/137486803-69ff151a-bb01-495a-abb8-7801ad72fd8a.png)

**Comment by l3nnartt** [comment]
but why

**Comment by octylFractal** [comment]
If I recall correctly, I rejected the PR due to it occuring during Hacktoberfest, and appearing to be a spam PR, plus it did not update the copyright everywhere. I don't know why I closed the associated issue, except perhaps that it was not very descriptive. Just posting an image isn't very helpful.

**Comment by l3nnartt** [comment]
alright
