### ISSUE TITLE
Add an offset in the `//stack` command

### ISSUE THREAD

**Issue by foxypiratecove37350** [EngineHub/WorldEditDocs#58]
Hello,

I'm using the `//stack` command, but I want that the copied versions of the selection have a gap between them (for example, 2 blocks, or also -1 block to shift it to fit inside the previous copy by 1 block). I fond in the documention the `[offset]` parameter, but as shown in the issue #31, it's more a direction than an offset. I think there is no current way to do that I want so I post this feature as a enhancement idea.

Thanks.

**Comment by octylFractal** [comment]
(1) This is the wrong repo for this, as you're requesting a WorldEdit feature, not a docs change.
(2) You can pass `-r` to use block units instead of the size of the selection. This is documented in the `//help stack` and the [command page](https://worldedit.enginehub.org/en/latest/commands/#command-//stack), but as mentioned in that issue the other doc pages need to be updated manually and no one's taken the time to do that.

Reference https://github.com/EngineHub/WorldEdit/issues/1443.

**Comment by foxypiratecove37350** [comment]
Oh sh**sse I didn't saw this. Thanks @octylFractal
